export type Archetype = 'Realistic' | 'Investigative' | 'Artistic' | 'Social' | 'Enterprising' | 'Conventional';

export interface RiasetActivity {
    text: string;
    archetype: Archetype;
}

// 72 activities, 12 for each archetype, shuffled together.
export const activities: RiasetActivity[] = [
    { text: 'Build a cabinet or furniture', archetype: 'Realistic' },
    { text: 'Study the structure of the human body', archetype: 'Investigative' },
    { text: 'Write a novel or a play', archetype: 'Artistic' },
    { text: 'Teach adults how to read', archetype: 'Social' },
    { text: 'Manage a retail store', archetype: 'Enterprising' },
    { text: 'Keep detailed financial records', archetype: 'Conventional' },
    { text: 'Repair a car or bicycle', archetype: 'Realistic' },
    { text: 'Work in a biology or chemistry lab', archetype: 'Investigative' },
    { text: 'Play a musical instrument in a band', archetype: 'Artistic' },
    { text: 'Help people with personal or emotional problems', archetype: 'Social' },
    { text: 'Start your own business', archetype: 'Enterprising' },
    { text: 'Organize a company\'s office systems', archetype: 'Conventional' },
    { text: 'Work on a construction site', archetype: 'Realistic' },
    { text: 'Develop a new scientific theory', archetype: 'Investigative' },
    { text: 'Design a logo for a new company', archetype: 'Artistic' },
    { text: 'Work as a volunteer for a cause you believe in', archetype: 'Social' },
    { text: 'Give a speech at a conference', archetype: 'Enterprising' },
    { text: 'Operate a calculator or data entry machine', archetype: 'Conventional' },
    { text: 'Operate heavy machinery', archetype: 'Realistic' },
    { text: 'Analyze data to identify trends', archetype: 'Investigative' },
    { text: 'Create special effects for movies', archetype: 'Artistic' },
    { text: 'Plan community events or activities', archetype: 'Social' },
    { text: 'Sell a product or service', archetype: 'Enterprising' },
    { text: 'Proofread documents for errors', archetype: 'Conventional' },
    { text: 'Work outdoors, for example in forestry or farming', archetype: 'Realistic' },
    { text: 'Solve complex mathematical problems', archetype: 'Investigative' },
    { text: 'Paint a mural or a portrait', archetype: 'Artistic' },
    { text: 'Counsel people about their careers', archetype: 'Social' },
    { text: 'Negotiate business deals', archetype: 'Enterprising' },
    { text: 'Create and manage a detailed budget', archetype: 'Conventional' },
    { text: 'Assemble electronic parts', archetype: 'Realistic' },
    { text: 'Investigate the cause of a fire or crime', archetype: 'Investigative' },
    { text: 'Act in a play or movie', archetype: 'Artistic' },
    { text: 'Take care of children at a daycare center', archetype: 'Social' },
    { text: 'Lead a team to achieve a goal', archetype: 'Enterprising' },
    { text: 'Use a computer to organize information', archetype: 'Conventional' },
    { text: 'Do plumbing or electrical work', archetype: 'Realistic' },
    { text: 'Study the movement of planets and stars', archetype: 'Investigative' },
    { text: 'Take professional photographs', archetype: 'Artistic' },
    { text: 'Mediate a dispute between people', archetype: 'Social' },
    { text: 'Buy and sell stocks and bonds', archetype: 'Enterprising' },
    { text: 'Check documents for accuracy and completeness', archetype: 'Conventional' },
    { text: 'Set up and operate machines to make products', archetype: 'Realistic' },
    { text: 'Do research to find a cure for a disease', archetype: 'Investigative' },
    { text: 'Compose or arrange music', archetype: 'Artistic' },
    { text: 'Provide care to sick or injured people', archetype: 'Social' },
    { text: 'Run for a political office', archetype: 'Enterprising' },
    { text: 'Follow a set plan to perform a task', archetype: 'Conventional' },
    { text: 'Work with your hands and tools', archetype: 'Realistic' },
    { text: 'Examine blood samples with a microscope', archetype: 'Investigative' },
    { text: 'Write scripts for movies or television', archetype: 'Artistic' },
    { text: 'Train new employees at a company', archetype: 'Social' },
    { text: 'Manage a department within a large company', archetype: 'Enterprising' },
    { text: 'File documents in an organized system', archetype: 'Conventional' },
    { text: 'Drive a truck or a forklift', archetype: 'Realistic' },
    { text: 'Study ways to reduce water pollution', archetype: 'Investigative' },
    { text: 'Perform as a dancer or singer', archetype: 'Artistic' },
    { text: 'Supervise the work of others', archetype: 'Social' },
    { text: 'Create a marketing campaign for a product', archetype: 'Enterprising' },
    { text: 'Keep shipping and receiving records', archetype: 'Conventional' },
    { text: 'Test the quality of parts before shipment', archetype: 'Realistic' },
    { text: 'Interpret the results of a scientific study', archetype: 'Investigative' },
    { text: 'Decorate the interior of a home or building', archetype: 'Artistic' },
    { text: 'Give guidance to people about their personal lives', archetype: 'Social' },
    { text: 'Be in charge of a company or organization', archetype: 'Enterprising' },
    { text: 'Handle customer payments and record transactions', archetype: 'Conventional' },
    { text: 'Use precision machines to build custom metal parts', archetype: 'Realistic' },
    { text: 'Write a scientific or technical article', archetype: 'Investigative' },
    { text: 'Create illustrations for a book', archetype: 'Artistic' },
    { text: 'Work with elderly people', archetype: 'Social' },
    { text: 'Persuade others to your point of view', archetype: 'Enterprising' },
    { text: 'Develop or manage a database', archetype: 'Conventional' }
];